import {useState,type FormEvent} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useDemoSession} from '../app/DemoSession';
import {ErrorNote,Field,useAction} from '../app/ui';
export function AuthPage({register=false}:{register?:boolean}){
 const {api,accept,user}=useDemoSession();const navigate=useNavigate();const a=useAction();
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [profileName,setProfileName]=useState('');const [role,setRole]=useState<'business'|'team'>('business');
 async function submit(e:FormEvent){e.preventDefault();await a.run(async()=>{const session=register?await api.register({email,password,name,role,profile_name:profileName}):await api.login({email,password});accept(session);navigate(session.user.profile.role==='business'?'/business':'/catalog');});}
 if(user)return <div className="empty"><h1>Вы уже вошли</h1><Link className="button" to="/catalog">Открыть каталог</Link></div>;
 return <div className="auth-layout"><section className="auth-story"><h1>Реальные задачи.<br/><span>Ваш следующий<br/>проект.</span></h1><p>Бизнес формулирует задачу.<br/>Команды предлагают решения.<br/>Результат подтверждается делом.</p><div className="auth-path"><span>Задача</span><i/><span>Команда</span><i/><span>Результат</span></div><p className="auth-footnote">Qadam · От задачи к результату</p></section><section className="auth-form"><h2>{register?'Создать аккаунт':'С возвращением'}</h2><p className="muted">{register?'Представьтесь и выберите, как будете работать.':'Войдите, чтобы продолжить работу над проектами.'}</p><ErrorNote text={a.error}/><form onSubmit={submit}><fieldset disabled={a.busy}>
 {register&&<><div className="role-choice" aria-label="Тип аккаунта"><button type="button" aria-pressed={role==='business'} onClick={()=>setRole('business')}>Я представляю бизнес</button><button type="button" aria-pressed={role==='team'} onClick={()=>setRole('team')}>Я в команде</button></div><Field label="Ваше имя" name="name" value={name} onChange={setName} required autoComplete="name"/><Field label={role==='business'?'Название организации':'Название команды'} name="profile_name" value={profileName} onChange={setProfileName} required/></>}
 <Field label="Email" name="email" type="email" value={email} onChange={setEmail} required autoComplete="email"/><Field label="Пароль" name="password" type="password" value={password} onChange={setPassword} required minLength={register?12:undefined} autoComplete={register?'new-password':'current-password'}/>{register&&<small className="muted">Не менее 12 символов. Пароль принадлежит вашему личному аккаунту.</small>}
 <button className="primary full" type="submit">{a.busy?'Подождите…':register?'Создать аккаунт':'Войти'}</button></fieldset></form><p className="auth-switch">{register?'Уже есть аккаунт?':'Первый раз здесь?'} <Link to={register?'/login':'/register'}>{register?'Войти':'Зарегистрироваться'}</Link></p></section></div>;
}
