import {useEffect,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import type {TaskFields,TaskResponse} from '../api/types';
import {useDemoSession} from '../app/DemoSession';
import {emptyFields,ErrorNote,Field,fields,Loading,message,PageTitle,RatingPanel,useAction} from '../app/ui';
import {readDraft,removeDraft,saveDraft} from '../app/storage';
export function ConstructorPage(){
 const {api,selectedIdentity}=useDemoSession();const [params,setParams]=useSearchParams();const id=params.get('task');
 const key=selectedIdentity!.id+':constructor:'+(id??'new');const a=useAction();
 const [task,setTask]=useState<TaskResponse|null>(null);const [values,setValues]=useState<TaskFields>(()=>readDraft(key,emptyFields));
 const [questions,setQuestions]=useState<string[]>([]);const [answers,setAnswers]=useState<Record<string,string>>({});
 const [source,setSource]=useState<string|null>(null);const [loading,setLoading]=useState(!!id);const [notice,setNotice]=useState('');
 useEffect(()=>{if(!id)return;let active=true;void api.task(id).then(t=>{if(active){setTask(t);setValues(readDraft(key,t));setLoading(false);}}).catch(e=>{if(active){a.setError(message(e));setLoading(false);}});return()=>{active=false;};},[api,id,key]);
 function edit(field:keyof TaskFields,value:string){const next={...values,[field]:value};setValues(next);saveDraft(key,next);setNotice('Есть несохранённые изменения');}
 const dirty=task?fields.some(f=>task[f.key]!==values[f.key]):true;
 async function save(){const result=task?(dirty?await api.updateTask(task.id,values):task):await api.createTask(values);setTask(result);setValues(result);removeDraft(key);return result;}
 function apply(t:TaskResponse){setTask(t);setValues(t);removeDraft(key);}
 async function create(e:FormEvent){e.preventDefault();await a.run(async()=>{const t=await save();setParams({task:t.id},{replace:true});});}
 if(loading)return <Loading/>;
 if(!task&&id)return <><ErrorNote text={a.error}/><Link to="/business">Вернуться к задачам</Link></>;
 if(!task)return <><PageTitle title="С чего начнём?" description="Опишите проблему своими словами. Система поможет собрать задачу для команды."/><div className="start-layout"><form className="panel" onSubmit={create}><ErrorNote text={a.error}/><Field label="Какую задачу нужно решить?" name="need" value={values.need} onChange={v=>edit('need',v)} multiline required hint="Например: обращения клиентов теряются между отделами, а мы не видим, кто за них отвечает."/><Field label="Тема или отрасль" name="topic" value={values.topic} onChange={v=>edit('topic',v)} hint="Поддержка клиентов, образование, логистика"/><button className="primary" disabled={a.busy}>{a.busy?'Создаём…':'Создать черновик'}</button></form><aside className="explain"><h2>Хорошая задача<br/>начинается с контекста.</h2><p>Не нужно сразу знать все ответы. Расскажите, что происходит сейчас и что хотите изменить.</p><ol><li>Опишите потребность</li><li>Ответьте на уточнения</li><li>Подтвердите и опубликуйте</li></ol></aside></div></>;
 return <><PageTitle title={task.title||'Конструктор задачи'} description="Уточните сведения, подтвердите карточку и отдельно опубликуйте её." action={<Link className="button secondary" to="/business">Мои задачи</Link>}/>
 <div className="flow-steps" aria-label="Подготовка задачи"><span className="done">Описание</span><span className={task.confirmed&&!dirty?'done':'current'}>Карточка</span><span className={task.confirmed&&!dirty?'done':''}>Подтверждение</span><span className={task.published?'done':''}>Публикация</span></div>
 <ErrorNote text={a.error}/>{notice&&<div className="notice" role="status">{notice}</div>}
 {task.published&&<div className="notice">В каталоге хранится последняя опубликованная версия. Правки появятся после повторной публикации. <Link to={'/catalog/'+task.id}>Посмотреть в каталоге</Link></div>}
 <div className="editor-layout"><div><section className="panel question-panel"><div className="section-top"><div><h2>Уточняющие вопросы</h2><p className="muted">Добавим то, чего не хватает команде для старта.</p></div><button disabled={a.busy} onClick={()=>void a.run(async()=>{const t=await save();apply(t);const r=await api.questions(t.id);setQuestions(r.data.questions);setSource(r.source);setNotice('Ответьте на вопросы ниже.');})}>{a.busy?'Подождите…':questions.length?'Обновить вопросы':'Получить вопросы'}</button></div>
 {source&&<p className="source">{source==='openai'?'Помощник AI':'Локальный помощник · внешний AI не использовался'}</p>}
 {questions.length>0&&<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{const t=await save();const r=await api.composeTask(t.id,questions.map(q=>({question:q,answer:answers[q]??''})));apply(r.data);setSource(r.source);setQuestions([]);setAnswers({});setNotice('Ответы добавлены. Проверьте карточку перед подтверждением.');});}}><fieldset disabled={a.busy}>{questions.map((q,i)=><Field key={q} label={q} name={'answers.'+i+'.answer'} value={answers[q]??''} onChange={v=>setAnswers({...answers,[q]:v})} multiline/>)}<button className="primary">Добавить ответы в карточку</button></fieldset></form>}</section>
 <form className="panel" onSubmit={e=>{e.preventDefault();void a.run(async()=>{apply(await save());setNotice('Карточка сохранена.');});}}><h2>Карточка задачи</h2><fieldset disabled={a.busy}><div className="form-grid">{fields.map(f=><div key={f.key} className={f.key==='title'||f.key==='topic'?'':'span-two'}><Field label={f.label} name={f.key} value={values[f.key]} onChange={v=>edit(f.key,v)} multiline={!['title','topic','contact'].includes(f.key)} hint={f.hint}/></div>)}</div><div className="actions"><button type="submit" className="primary" disabled={!dirty}>Сохранить изменения</button><span className="muted">{dirty?'Изменения ещё не сохранены':'Все изменения сохранены'}</span></div></fieldset></form></div>
 <div className="editor-side"><RatingPanel rating={task.rating} confirmed={task.confirmed&&!dirty}/><section className="publish-actions"><h2>Готово к публикации?</h2><p>Подтверждаю, что сведения в карточке верны и их можно передать командам.</p><button className="full" disabled={a.busy||(task.confirmed&&!dirty)} onClick={()=>void a.run(async()=>{const t=await save();apply(await api.confirmTask(t.id));setNotice('Сведения подтверждены. Рейтинг пересчитан.');})}>{task.confirmed&&!dirty?'Сведения подтверждены':'Подтвердить сведения'}</button><button className="primary full" disabled={a.busy||dirty||!task.confirmed} onClick={()=>void a.run(async()=>{apply(await api.publishTask(task.id));setNotice('Задача опубликована и доступна всем командам.');})}>{task.published?'Обновить публикацию':'Опубликовать задачу'}</button></section></div></div></>;
}
