import {useEffect,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import type {ProposalResponse,TaskResponse,TeamProposalList} from '../api/types';
import {useDemoSession} from '../app/DemoSession';
import {ErrorNote,Field,Loading,PageTitle,ProfileLink,SafeLink,statusLabels,useAction} from '../app/ui';
export function BusinessPage(){const {api}=useDemoSession();const [tasks,setTasks]=useState<TaskResponse[]>([]);const [selected,setSelected]=useState<string|null>(null);const [loading,setLoading]=useState(true);const a=useAction();
 async function load(){await a.run(async()=>{setTasks((await api.businessTasks()).items);setLoading(false);});setLoading(false);}
 useEffect(()=>{void load();},[api]);
 return <><PageTitle title="Мои задачи" description="От первых набросков до подтверждённых результатов." action={<Link className="button primary" to="/constructor">Создать задачу</Link>}/><ErrorNote text={a.error}/><div className="section-top"><h2>{tasks.length} задач в работе</h2><button disabled={a.busy} onClick={()=>void load()}>Обновить</button></div>{loading?<Loading/>:tasks.length===0?<div className="empty"><h2>Ваша первая задача начинается здесь</h2><p>Расскажите, что нужно изменить в бизнесе. Команды помогут найти решение.</p><Link className="button primary" to="/constructor">Описать задачу</Link></div>:<div className="workspace-list">{tasks.map(t=><article className="work-row" key={t.id}><div className="section-top"><div><div className="meta"><span>{t.topic||'Без темы'}</span><span className="badge">{t.published?'Опубликована':'Черновик'}</span>{!t.confirmed&&<span className="badge warning">Нужно подтвердить</span>}</div><h2>{t.title||t.need||'Без названия'}</h2><p className="muted">Текущий рейтинг {t.rating.total}/100{t.published_rating?' · В каталоге '+t.published_rating.total+'/100':''}</p></div><div className="actions"><Link className="button" to={'/constructor?task='+t.id}>Редактировать</Link><button className={selected===t.id?'primary':''} onClick={()=>setSelected(selected===t.id?null:t.id)}>{selected===t.id?'Скрыть предложения':'Предложения'}</button>{t.published&&<Link to={'/catalog/'+t.id}>В каталоге</Link>}</div></div>{selected===t.id&&<BusinessProposals taskId={t.id}/>}</article>)}</div>}</>;
}
function BusinessProposals({taskId}:{taskId:string}){const {api}=useDemoSession();const [items,setItems]=useState<ProposalResponse[]|null>(null);const a=useAction();
 async function load(){await a.run(async()=>setItems((await api.proposals(taskId)).items));}
 useEffect(()=>{void load();},[api,taskId]);
 function update(p:ProposalResponse){setItems(current=>current?.map(x=>x.id===p.id?p:x)??null);}
 return <section className="proposals-section"><div className="section-top"><h3>Предложения команд</h3><button disabled={a.busy} onClick={()=>void load()}>Обновить предложения</button></div><ErrorNote text={a.error}/>{!items?(a.error?null:<Loading/>):items.length===0?<p className="muted">Предложений пока нет. Команды смогут откликнуться после публикации.</p>:items.map(p=><div className="proposal-item" key={p.id}><div className="section-top"><ProfileLink id={p.team_id}/><span className={'badge '+p.status}>{statusLabels[p.status]}</span></div><h3>{p.idea}</h3><p className="preline">{p.plan}</p><div className="meta"><span>Срок: {p.duration}</span><SafeLink url={p.prototype_url} label="Прототип"/></div><div className="actions"><button disabled={a.busy||!!p.milestone||p.status==='selected'} className="primary" onClick={()=>void a.run(async()=>update(await api.decideProposal(p.id,'selected')))}>Выбрать команду</button><button disabled={a.busy||!!p.milestone||p.status==='rejected'} onClick={()=>void a.run(async()=>update(await api.decideProposal(p.id,'rejected')))}>Отклонить</button></div>{p.milestone&&<StageReview proposal={p} onChange={update}/>}</div>)}</section>;
}
function StageReview({proposal,onChange}:{proposal:ProposalResponse;onChange:(p:ProposalResponse)=>void}){const {api}=useDemoSession();const stage=proposal.milestone!;const [comment,setComment]=useState('');const a=useAction();
 return <section className="stage"><div className="section-top"><h3>Результат этапа</h3><span className="badge">{statusLabels[stage.status]}</span></div><p className="preline">{stage.description}</p><SafeLink url={stage.result_url} label="Открыть результат"/>{stage.comment&&<p>Комментарий: {stage.comment}</p>}<ErrorNote text={a.error}/>{stage.status==='submitted'&&<><Field label="Комментарий для доработки" name="comment" value={comment} onChange={setComment} multiline hint="Что необходимо исправить или дополнить?"/><div className="actions"><button className="primary" disabled={a.busy} onClick={()=>void a.run(async()=>{const m=await api.reviewMilestone(stage.id,'confirmed',comment);onChange({...proposal,milestone:m});})}>Подтвердить результат</button><button disabled={a.busy||!comment.trim()} onClick={()=>void a.run(async()=>{const m=await api.reviewMilestone(stage.id,'changes_requested',comment);onChange({...proposal,milestone:m});})}>Вернуть на доработку</button></div></>}{stage.status==='confirmed'&&<p className="success-text">Команде начислено {stage.points_awarded} баллов.</p>}</section>;
}
export function TeamPage(){const {api}=useDemoSession();const [data,setData]=useState<TeamProposalList|null>(null);const a=useAction();
 async function load(){await a.run(async()=>setData(await api.teamProposals()));}
 useEffect(()=>{void load();},[api]);
 return <><PageTitle title="Моя работа" description="Ваши предложения, выбранные проекты и результаты." action={<Link className="button primary" to="/catalog">Найти задачу</Link>}/><div className="team-summary"><div><strong>{data?.team_points??0}</strong><span>баллов за подтверждённые результаты</span></div><button disabled={a.busy} onClick={()=>void load()}>Обновить статусы</button></div><ErrorNote text={a.error}/>{!data?(a.error?null:<Loading/>):data.items.length===0?<div className="empty"><h2>Здесь будут ваши проекты</h2><p>Выберите задачу в каталоге и предложите свой подход.</p><Link to="/catalog">Перейти к задачам</Link></div>:<div className="workspace-list">{data.items.map(p=><TeamProposal key={p.id} proposal={p} refresh={load}/>)}</div>}</>;
}
function TeamProposal({proposal:p,refresh}:{proposal:ProposalResponse;refresh:()=>Promise<void>}){const {api}=useDemoSession();const a=useAction();const [description,setDescription]=useState(p.milestone?.description??'');const [url,setUrl]=useState(p.milestone?.result_url??'');const [title,setTitle]=useState('Задача бизнеса');
 useEffect(()=>{let active=true;void api.task(p.task_id).then(t=>{if(active)setTitle(t.title||t.need||'Задача бизнеса');}).catch(()=>{});return()=>{active=false;};},[api,p.task_id]);
 async function submit(e:FormEvent){e.preventDefault();if(!/^https?:\/\//i.test(url)){a.setError('Ссылка должна начинаться с http:// или https://');return;}await a.run(async()=>{await api.createMilestone(p.id,{description,result_url:url});await refresh();});}
 return <article className="work-row"><div className="section-top"><Link to={'/catalog/'+p.task_id}>{title}</Link><span className={'badge '+p.status}>{statusLabels[p.status]}</span></div><h2>{p.idea}</h2><p className="preline">{p.plan}</p><div className="meta"><span>Срок: {p.duration}</span><SafeLink url={p.prototype_url} label="Прототип"/></div>
 {p.milestone&&<section className="stage"><h3>{statusLabels[p.milestone.status]}</h3><p className="preline">{p.milestone.description}</p><SafeLink url={p.milestone.result_url} label="Открыть результат"/>{p.milestone.comment&&<div className="notice">Комментарий бизнеса: {p.milestone.comment}</div>}{p.milestone.status==='confirmed'&&<p className="success-text">+{p.milestone.points_awarded} баллов за этап</p>}</section>}
 {p.status==='selected'&&(!p.milestone||p.milestone.status==='changes_requested')&&<form className="stage" onSubmit={submit}><h3>{p.milestone?'Пересдать результат':'Отправить результат этапа'}</h3><ErrorNote text={a.error}/><fieldset disabled={a.busy}><Field label="Что сделано" name="description" value={description} onChange={setDescription} multiline required/><Field label="Ссылка на результат" name="result_url" value={url} onChange={setUrl} type="url" required hint="https://"/><button className="primary">{a.busy?'Отправляем…':p.milestone?'Отправить повторно':'Отправить на проверку'}</button></fieldset></form>}</article>;
}
