import {useEffect,useState,type FormEvent} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import type {Profile} from '../api/types';
import {useDemoSession} from '../app/DemoSession';
import {ErrorNote,Field,Loading,PageTitle,SafeLink,useAction} from '../app/ui';
export function ProfilePage(){const {profileId}=useParams();const s=useDemoSession();const [profile,setProfile]=useState<Profile|null>(profileId?null:s.selectedIdentity);const [name,setName]=useState(s.user?.name??'');const a=useAction();const [saved,setSaved]=useState('');const [current,setCurrent]=useState('');const [password,setPassword]=useState('');const navigate=useNavigate();
 useEffect(()=>{if(profileId)void a.run(async()=>setProfile(await s.api.profile(profileId)));},[profileId,s.api]);
 function edit<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>p?{...p,[key]:value}:null);setSaved('');}
 async function save(e:FormEvent){e.preventDefault();if(!profile)return;await a.run(async()=>{await s.api.updateUser(name);const {name:n,description,industry,website,contact,interests,skills,technologies,portfolio_urls}=profile;setProfile(await s.api.updateProfile({name:n,description,industry,website,contact,interests,skills,technologies,portfolio_urls:portfolio_urls.map(u=>u.trim()).filter(Boolean)}));await s.reload();setSaved('Профиль сохранён');});}
 if(!profile)return <><ErrorNote text={a.error}/>{a.error?<button disabled={a.busy} onClick={()=>void a.run(async()=>setProfile(await s.api.profile(profileId!)))}>Повторить загрузку профиля</button>:<Loading/>}</>;
 if(profileId)return <><PageTitle title={profile.name} description={profile.role==='business'?'Профиль бизнеса':'Профиль команды'}/><div className="panel public-profile"><p className="preline">{profile.description||'Описание ещё не добавлено.'}</p><div className="tag-list">{[...profile.interests,...profile.skills,...profile.technologies].map((v,i)=><span className="badge" key={i}>{v}</span>)}</div>{profile.industry&&<p>Направление: {profile.industry}</p>}{profile.contact&&<p>Контакт: {profile.contact}</p>}<SafeLink url={profile.website} label="Сайт"/>{profile.portfolio_urls.map(u=><p key={u}><SafeLink url={u} label={u}/></p>)}{profile.role==='team'&&<p>Баллы за подтверждённые результаты: <strong>{profile.team_points}</strong></p>}<h2>Участники</h2>{profile.members.map((m,i)=><p key={i}>{m.name}</p>)}</div></>;
 return <><PageTitle title="Мой профиль" description="Расскажите о себе и о том, над чем хотите работать."/><ErrorNote text={a.error}/>{saved&&<div className="notice" role="status">{saved}</div>}<form className="panel profile-editor" onSubmit={save}><fieldset disabled={a.busy}><h2>Личный аккаунт</h2><div className="form-grid"><Field label="Ваше имя" name="name" value={name} onChange={setName} required/><div className="form-field"><span>Email для входа</span><p className="readonly">{s.user?.email}</p><small className="muted">Виден только вам.</small></div></div><h2>{profile.role==='business'?'Профиль бизнеса':'Профиль команды'}</h2><Field label="Название" name="profile_name" value={profile.name} onChange={v=>edit('name',v)} required/><Field label="Описание" name="description" value={profile.description} onChange={v=>edit('description',v)} multiline/><div className="form-grid"><Field label="Направление" name="industry" value={profile.industry} onChange={v=>edit('industry',v)}/><Field label="Сайт" name="website" value={profile.website} onChange={v=>edit('website',v)} type="url"/><Field label="Публичный контакт" name="contact" value={profile.contact} onChange={v=>edit('contact',v)}/><Tags label="Интересы" value={profile.interests} onChange={v=>edit('interests',v)}/>{profile.role==='team'&&<><Tags label="Навыки" value={profile.skills} onChange={v=>edit('skills',v)}/><Tags label="Технологии" value={profile.technologies} onChange={v=>edit('technologies',v)}/></>}</div><Field label="Ссылки на портфолио, каждая с новой строки" name="portfolio_urls" value={profile.portfolio_urls.join('\n')} onChange={v=>edit('portfolio_urls',v.split('\n'))} multiline/><p className="muted">Описание и публичные контакты увидят другие участники.</p><button className="primary">Сохранить профиль</button></fieldset></form><form className="panel profile-editor" onSubmit={e=>{e.preventDefault();void a.run(async()=>{await s.api.changePassword({current_password:current,new_password:password});await s.reload();navigate('/login');});}}><h2>Сменить пароль</h2><p className="muted">После смены пароля потребуется заново войти на всех устройствах.</p><fieldset disabled={a.busy}><div className="form-grid"><Field label="Текущий пароль" name="current_password" value={current} onChange={setCurrent} type="password" required autoComplete="current-password"/><Field label="Новый пароль, минимум 12 символов" name="new_password" value={password} onChange={setPassword} type="password" required minLength={12} autoComplete="new-password"/></div><button>Изменить пароль</button></fieldset></form></>;
}
function Tags({label,value,onChange}:{label:string;value:string[];onChange:(v:string[])=>void}){const [text,setText]=useState(value.join(', '));return <Field label={label+' через запятую'} name={label} value={text} onChange={v=>{setText(v);onChange(v.split(',').map(s=>s.trim()).filter(Boolean));}}/>;}
